config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/resource-catalogue:
      branch: master
      repo: https://github.com/madgeek-arc/resource-catalogue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/resource-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-green-spoonbill.sh
        container: qc.acc_slaphappy-aqua-uakari
  QC.Doc:
    repos:
      github.com/madgeek-arc/resource-catalogue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cerise-cuscus.sh
        container: qc.doc_bluesy-amethyst-collie
      github.com/madgeek-arc/resource-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-silver-terrier.sh
        container: qc.doc_freaky-tangerine-quail
      github.com/madgeek-arc/resource-catalogue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-gamboge-monster.sh
        container: qc.doc_gamy-zucchini-donkey
  QC.Lic:
    repos:
      github.com/madgeek-arc/resource-catalogue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cinnabar-jackal.sh
        container: qc.lic_hazy-cinnabar-chow
  QC.Sty:
    repos:
      github.com/madgeek-arc/resource-catalogue checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-black-hyena.sh
        container: qc.sty_grumpy-scarlet-kakapo
      github.com/madgeek-arc/resource-catalogue hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-heliotrope-rabbit.sh
        container: qc.sty_leaky-sangria-caiman
      github.com/madgeek-arc/resource-catalogue jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-chartreuse-dunker.sh
        container: qc.sty_slimy-tangerine-walrus
  QC.Ver:
    repos:
      github.com/madgeek-arc/resource-catalogue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-amethyst-ocelot.sh
        container: qc.ver_blurry-eggplant-gibbon
timeout: 5400
