config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/resource-catalogue:
      branch: master
      repo: https://github.com/madgeek-arc/resource-catalogue
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/resource-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-olivine-swan.sh
        container: qc.acc_fuzzy-linen-mole
  QC.Doc:
    repos:
      github.com/madgeek-arc/resource-catalogue find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-harlequin-barb.sh
        container: qc.doc_sleepy-rose-giraffe
      github.com/madgeek-arc/resource-catalogue git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-linen-koala.sh
        container: qc.doc_pokey-russet-caracal
      github.com/madgeek-arc/resource-catalogue markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cobalt-hamster.sh
        container: qc.doc_bluesy-plum-clam
  QC.Lic:
    repos:
      github.com/madgeek-arc/resource-catalogue licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-fuchsia-hyena.sh
        container: qc.lic_lanky-asparagus-spider
  QC.Sty:
    repos:
      github.com/madgeek-arc/resource-catalogue checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-tangerine-ant.sh
        container: qc.sty_chummy-coral-cattle
      github.com/madgeek-arc/resource-catalogue hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-sangria-kudu.sh
        container: qc.sty_sunny-pink-blue
      github.com/madgeek-arc/resource-catalogue jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-wisteria-eagle.sh
        container: qc.sty_lousy-lemon-bonobo
  QC.Ver:
    repos:
      github.com/madgeek-arc/resource-catalogue get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-myrtle-kangaroo.sh
        container: qc.ver_messy-silver-schnauzer
timeout: 5400
